### ISSUE TITLE
Should setting __slots__ be the default

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#10]
In point 5 of issue #9, @ilevkivskyi suggests that setting __slots__ should be the default, and setting slots=False would allow the caller to opt out of this behavior.

Given the typical use cases for this feature, I tend to agree. I'm opening this issue for discussion of this point.

**Comment by warsaw** [comment]
It seems reasonable to me.  Most of the attrs classes I've used don't have any need for dynamic addition of attributes.

**Comment by gvanrossum** [comment]
Slots are normally an opt-in feature. IIRC one of the requirements for the new class decorator is that the resulting class is "just a regular class". I think it's great to make slots possible, but not by default.

(Also, depending on the base classes, there may already be a `__dict__` anyways.)

**Comment by hynek** [comment]
So the point of attrs/dataclasses is that you usually want to pre-define the design of your classes and I’ve found in practice that I almost always set slots to true on my attrs classes.  If I started from scratch, it would most certainly be the default today.

I would go as far as telling the user that there is a `__dict__` present and force them to set slots to False, such that the system doesn’t silently do things they don’t expect but a “smart” approach of doing the best possible thing is fine with me too.

In the end it gives you the benefit of seeing on first sight whether or not additional attributes are patched on the class which I find a very useful information.

**Comment by ilevkivskyi** [comment]
An additional point to @hynek arguments is that static type checkers like mypy behave as if all classes had ``__slots__``. They prohibit "patching" the class/instances after the class is created:
```python
class C:
    x: int

C().y = 1  #  mypy error: "C" has no attribute "y"
C.y = 1  # mypy error: Type[C] has no attribute "y"
```

**Comment by ericvsmith** [comment]
I'm torn. I think that setting `__slots` is the right thing in 95% of the cases. Although in 95% of those cases, it won't matter. (Numbers made up.)

In favor of `slots=True` being the default:
1. It's probably the right behavior, most of the time.
2. mypy assumes similar behavior to having `__slots__` set, and by using type annotations we're sort of leaning in the typing/mypy direction.

In favor of `slots=False` being the default:
1. Everywhere else in Python, you have to explicitly set `__slots__`.
2. It fits more in line with the ethos of "just add some members to this class", not "return a new class".

Maybe have two different decorator, `@dataclass` and `@dataclass_slots` (or whatever names)? But that seems like a lot of cognitive overhead just to avoid `slots=True`. Probably a single decorator is best, and we just document what the defaults are and how to get the other behavior.

**Comment by hynek** [comment]
FWIW I'm not gonna die on this hill and the other issues I've raised are more important to me.  I don't see any advantage of a _slots suffix and plenty downsides.  :)

**Comment by ericvsmith** [comment]
I don't feel very strongly about it, either. Let's just leave `slots=False` for now. We can always argue it out when we move it to python-dev. I'll mention it in the PEP as an issue, which should spark discussion.
