### ISSUE TITLE
__name__ vs __qualname__ in dataclass __repr__

### ISSUE THREAD

**Issue by ariebovenberg** [ericvsmith/dataclasses#100]
What is the rationale for using the class `__name__` instead of `__qualname__` in a dataclass `__repr__`?
It seems like using `__qualname__` would keep nesting visible (the default for classes since PEP3155) without sacrificing succinctness for top-level classes.

Example to illustrate:

```python
@dataclass
class A:
     pass

class B:
    @dataclass
    class C:
        pass

def factory():
    @dataclass
    class D:
        pass
    return D
D = factory()
```

with `__name__` (current situation):

```python
>>> A()
A()
>>> B.C()
C()
>>> D()
D()
```

with `__qualname__`:

```python
>>> A()
A()
>>> B.C()
B.C()
>>> D()
factory.<locals>.D()
```

**Comment by ericvsmith** [comment]
It's just an oversight. I'll fix it.
