### ISSUE TITLE
Consider exposing _MISSING in the public API

### ISSUE THREAD

**Issue by tommikaikkonen** [ericvsmith/dataclasses#114]
I wrote [an integration for `dataclasses` in a pretty printer library](https://github.com/tommikaikkonen/prettyprinter/blob/b2a1e30884316349e54f094eedd4cc5139b4838a/prettyprinter/extras/dataclasses.py). In order for the integration to work well, I need the `_MISSING` constant value to determine if a field default or default factory is set.

`attrs` uses a public constant `attr.NOTHING` to facilitate that, whereas PEP557 explicitly says that `_MISSING` is private:

>The `_MISSING` value is a sentinel object used to detect if the default and default_factory parameters are provided. Users should never use `_MISSING` or depend on its value. This sentinel is used because `None` is a valid value for default.

For code that inspects dataclasses, it is highly useful to be able to determine if a field default is set or not. The current public API doesn't provide a way to do that.

[Discussion on whether `attr.NOTHING` should be public or private](https://github.com/python-attrs/attrs/issues/254)

**Comment by ericvsmith** [comment]
Yes, I think this is a good idea. I'm going to close this issue because I'm shutting down this repo, once I respond to all open issues.

I've opened https://bugs.python.org/issue32427 to track this.
