### ISSUE TITLE
Please explain some parts of your code.

### ISSUE THREAD

**Issue by godaygo** [ericvsmith/dataclasses#115]
Hi, I'm trying to re-implement yours dataclass idea through a `metaclass` instead of a decorator, and I'm a little bit confused about these [lines](https://github.com/ericvsmith/dataclasses/blob/e537aa52e59774cead498b252b8edc52699aadc5/dataclasses.py#L661-L697):
```python
def astuple(obj, *, tuple_factory=tuple):
    """Return the fields of a dataclass instance as a new tuple of field values.

    Example usage::

      @dataclass
      class C:
          x: int
          y: int

    c = C(1, 2)
    assert asdtuple(c) == (1, 2)

    If given, 'tuple_factory' will be used instead of built-in tuple.
    The function applies recursively to field values that are
    dataclass instances. This will also look into built-in containers:
    tuples, lists, and dicts.
    """


    if not _isdataclass(obj):
        raise TypeError("astuple() should be called on dataclass instances")
    return _astuple_inner(obj, tuple_factory)


def _astuple_inner(obj, tuple_factory):
    if _isdataclass(obj):
        result = []
        for f in fields(obj):
            value = _astuple_inner(getattr(obj, f.name), tuple_factory)
            result.append(value)
        return tuple_factory(result)
    elif isinstance(obj, (list, tuple)):
        return type(obj)(_astuple_inner(v, tuple_factory) for v in obj)
    elif isinstance(obj, dict):
        return type(obj)((_astuple_inner(k, tuple_factory), _astuple_inner(v, tuple_factory))
                          for k, v in obj.items())
    else:
        return deepcopy(obj)
```

I do not understand how to get into the `elif` branches, because `if not _isdataclass(obj):` in `astuple` and  `if _isdataclass(obj)` in `_astuple_inner:` are mutually exclusive (the same for `asdict` and `_asdict_inner`). What I'm missing? Thank you.

Also there is a typo in [docstring here](https://github.com/ericvsmith/dataclasses/blob/e537aa52e59774cead498b252b8edc52699aadc5/dataclasses.py#L672):
```python
    assert asdtuple(c) == (1, 2)
```
should be :

```python
    assert astuple(c) == (1, 2)
```

**Comment by taleinat** [comment]
`_astuple_inner()` can call itself recursively on its fields, which in many cases will not be dataclass instances.

**Comment by ericvsmith** [comment]
Thanks, @taleinat. Hopefully that's enough of an explanation for @godaygo,

**Comment by ilevkivskyi** [comment]
@godaygo Concerning the typo in docstring, could you please make a PR to ``python/cpython`` repo?

**Comment by godaygo** [comment]
@ilevkivskyi Yes of course, but I only have a phone up to Thursday.

@taleinat thank you, I was a little bit blind, the function name explains all:)
