### ISSUE TITLE
NameError when referencing cdataclass variable within list comprehension

### ISSUE THREAD

**Issue by andymcarter** [ericvsmith/dataclasses#116]
As described in the title, this file won't run despite all the variables being correctly defined. If I remove the reference to 'z' in the list comprehension it seems to be fine.

```
from dataclasses import dataclass

@dataclass
class TestDC:
    a = 3
    b = 4
    c = 5
    z = 10
    
    alphalist = [a,b,c]
    
    d,e,f = [(i+1)*z for i in alphalist]
```

Python 3.6

**Comment by taleinat** [comment]
This isn't related to `dataclasses`. The example fails without the `@dataclass` decorator as well.

**Comment by andymcarter** [comment]
Should have checked, sorry.

**Comment by taleinat** [comment]
@andymcarter, there's no need to apologize, I'm happy to help!
