### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by ukch** [ericvsmith/dataclasses#123]
I am looking at packaging this project for Debian, and I noticed that while setup.py mentions the MIT license, there is no explicit license file in the repo. In order to be 100% legal, please could you provide a license file?

**Comment by ericvsmith** [comment]
I'm not sure where I got the MIT reference. Most everything I do is Apache 2.0. If I change to that and add a license file, would that work for you?

**Comment by ukch** [comment]
Yes, I'm happy with either license, so long as there is clarity.

**Comment by ukch** [comment]
Come to think of it, since this is a fork of Python core code, shouldn't it be published under the [Python license](https://github.com/python/cpython/blob/master/LICENSE)?

**Comment by gvanrossum** [comment]
> to think of it, since this is a fork of Python core code, shouldn't it be
published under the Python license
<https://github.com/python/cpython/blob/master/LICENSE>?

Historically Eric wrote the code here first and then contributed it to the
PSF. So he can use any open source license he likes. (Though if he's
agreeable to it, the PSF license is fine too.)

**Comment by ericvsmith** [comment]
Fixed via #124. I went with Apache 2.0, since it makes my life easier (fewer things to check with the powers that be).
