### ISSUE TITLE
Keep type info in InitVar

### ISSUE THREAD

**Issue by reinhrst** [ericvsmith/dataclasses#126]
Right now `InitVar[something] is InitVar`. This means that any type-information is removed, and it will (for instance) be impossible to do type info checks on the generated `__init__`, or find out anything about the type of the variable.

**Comment by ericvsmith** [comment]
Can you raise this issue on bugs.python.org? This repo is now just for the back port to 3.6.

**Comment by reinhrst** [comment]
Thanks! Sorry, I was looking for that info, didn't find it anywhere :)

**Comment by reinhrst** [comment]
For reference: https://bugs.python.org/issue33569
