### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ukch** [ericvsmith/dataclasses#127]
I was wondering if you'd be able to do a new numbered release soon? The previous licensing issue (#123) means I can't package any previous version.

**Comment by ericvsmith** [comment]
Yes. My intent is to finish up the version for 3.7.0rc1, then post it on PyPI. It should be later this week. Does that work?

**Comment by ericvsmith** [comment]
I've pushed 0.6 to PyPI. It includes the work at the PyCon sprints, and I expect it will match the 3.7.0rc1 version.
