### ISSUE TITLE
Support fromdict

### ISSUE THREAD

**Issue by maximveksler** [ericvsmith/dataclasses#131]
Given class 

```python
@dataclass 
class A:
   a: str
   b: [A] = None
   c: {str: [A]} = None

a = A("foo")
```

It would be extremely useful, to be able to do something like this 

`a == fromdict(A, asdict(a))`
> True

**Comment by ericvsmith** [comment]
Can you bring this up on the python-ideas mailing list? This repo is just for the backport to Python 3.6. Thanks.
