### ISSUE TITLE
Dataclass inheritance behavior deviates from 3.7 implementation

### ISSUE THREAD

**Issue by shannonzhu** [ericvsmith/dataclasses#138]
PEP 557: https://www.python.org/dev/peps/pep-0557/#inheritance 

> it looks through all of the class's base classes in reverse MRO (that is, starting at object) and, for each Data Class that it finds, adds the fields from that base class

The PEP specifies that dataclasses should only inherit fields from parent classes that are themselves dataclasses. This is also the case at runtime in python3.7:

```
Python 3.7.0 (default, Jun 28 2018, 07:39:16)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dataclasses import dataclass
>>> class X:
... a: int
...
>>> @dataclass
... class Y(X):
... pass
...
>>> from dataclasses import fields
>>> fields(Y)
()
```

However, it appears that the backport implementation behaves differently:

```
Python 3.6.3rc1+ (default, Sep 19 2018, 12:28:39)
Type "help", "copyright", "credits" or "license" for more information.
>>> from dataclasses import dataclass
>>> class X:
... a: int
...
>>> @dataclass
... class Y(X):
... pass
...
>>> from dataclasses import fields
>>> fields(Y)
(Field(name='a',type=<class 'int'>,default=<dataclasses._MISSING_TYPE object at 0x7f6691d33978>,default_factory=<dataclasses._MISSING_TYPE object at 0x7f6691d33978>,init=True,repr=True,hash=None,compare=True,metadata={}),)
```

Is this something that looks like it should be fixed, or was this discrepancy intentional?

**Comment by ericvsmith** [comment]
That's a bug, although I can't imagine how it occurred, or how there's not a test to catch that.

But, I just tried it and did not get that behavior:
```
>>> dataclasses import *
>>> class X:
...   a: int
...

>>> @dataclass
... class Y(X): pass
...
>>> fields(Y)
()
```

So, I'm not sure what problem you're seeing. I really need to backport the current 3.7 version to this repo. I'm planning on doing that after I fix a few more bugs in 3.7.

**Comment by carljm** [comment]
Looks like this was the behavior on `dataclasses==0.4`, but is no longer the behavior on `dataclasses==0.6`. This issue can probably be closed.

**Comment by ericvsmith** [comment]
Thanks.
