### ISSUE TITLE
Annotated class variables

### ISSUE THREAD

**Issue by ilevkivskyi** [ericvsmith/dataclasses#14]
Is there a simple way to avoid including annotated (for the purpose of static checking) class variable into the list of fields? Ideally, it could be possible to just write:
```python
@easy
class C:
    x: int
    inst_count: ClassVar[int] = 0
```
Possible solution would be to just use a special marker for exclusion:
```python
@easy
class C:
    x: int
    inst_count: ClassVar[int] = classvar(0)  # Just inserts 0 here in generated code
```
I don't like re-using ``field`` here, since ``inst_count`` is _not_ actually a field.

**Comment by gvanrossum** [comment]
Why can't you just look for the presence of `ClassVar` in `__annotations__`?

**Comment by ilevkivskyi** [comment]
> Why can't you just look for the presence of ``ClassVar`` in ``__annotations__``?

This will be the only thing that requires importing ``typing``, which is quite a large module.
I would be glad to go with this solution, but this may induce some performance overhead.

**Comment by gvanrossum** [comment]
You could dynamically decide to import typing only if the full name of the type ends in ".ClassVar".

**Comment by ilevkivskyi** [comment]
OK, good point. And people who will use easy classes will most probably use ``typing`` anyway.

**Comment by ericvsmith** [comment]
Should we just bite the bullet and say that typing is required? Or is looking at a type name for ".ClassVar" good enough? I can't think of another place in Python where we look at a name of something, instead of it's actual type.

If we go with inspecting the name, what's the advantage of checking that the type name ends in ".ClassVar" instead of  "typing.ClassVar"?

**Comment by gvanrossum** [comment]
Let's just make typing a dependency of dataclasses and be done with it.

**Comment by ericvsmith** [comment]
I agree that it seems inevitable.

**Comment by ericvsmith** [comment]
Since I can't use isinstance or issubclass to check for ClassVar, what's the correct way to check that a type is a ClassVar? typing.py has a check for type(t).__name__ == '_ClassVar', but that seems fragile.

**Comment by gvanrossum** [comment]
I don't see an alternative -- we must see dataclasses as a close friend of typing.

**Comment by ericvsmith** [comment]
I'm currently accumulating all of the ClassVars in `__dataclass_classvars__`. I can't decide if this is useful, or not. I'll leave this issue open until I think it through. I'm leaning toward deleting it.

**Comment by gvanrossum** [comment]
It's redundant with information in `__attributes__` right? Also Ivan's [typing_inspect](https://github.com/ilevkivskyi/typing_inspect) has an `is_classvar()` that 3rd parties can use. (I don't recommend depending on this in dataclasses.

**Comment by ericvsmith** [comment]
My thinking was that it's hard to compute, but I agree it's not needed. You can always look at things in `__annotations__` and not in `__dataclass_fields__`. Or use typing_inspect, as you say.

**Comment by ilevkivskyi** [comment]
@ericvsmith FWIW ``is_classvar`` function in ``typing_inspect`` is just:
```python
type(tp) is _ClassVar
```
The point is that ``_ClassVar`` not only prohibits ``issuclass()`` and ``isinstance()``, but also prohibits subclassing. So that this check is quite reliable.

**Comment by ericvsmith** [comment]
Thanks, @ilevkivskyi.
