### ISSUE TITLE
Fix "dataclasses.replace broken if a class has any ClassVars" in backport

### ISSUE THREAD

**Issue by gnillev** [ericvsmith/dataclasses#143]
This bug https://bugs.python.org/issue33796 is still present in version 0.6 of the backport.
It would be nice to have a new backport version with the fix included.

**Comment by astronouth7303** [comment]
Bump, ran into this in ppb-vector.

**Comment by anthrotype** [comment]
@ericvsmith can we please have a new release of dataclasses backport with the fix in https://github.com/ericvsmith/dataclasses/pull/140 for ClassVar and .replace()? Thank you!!!

**Comment by anthrotype** [comment]
@ericvsmith Can you please cut a new release with #140 included? I need to use ClassVars with dataclasses and this prevents me from supporting python 3.6... I'm tempted to drop support for it altogether.

**Comment by ericvsmith** [comment]
@anthrotype : I've pushed 0.8 to PyPI. Please take a look.

**Comment by anthrotype** [comment]
now it works! thank you very much 👍

**Comment by ericvsmith** [comment]
No problem. Sorry for the extensive delay.
