### ISSUE TITLE
can not install on python 3.8 or high

### ISSUE THREAD

**Issue by jacksonjim** [ericvsmith/dataclasses#157]
ERROR: Package 'dataclasses' requires a different Python: 3.8.2 not in '>=3.6, <3.7'

**Comment by ericvsmith** [comment]
dataclasses is built in to python 3.7+, so there's no need to install it there.

**Comment by jacksonjim** [comment]
> dataclasses is built in to python 3.7+, so there's no need to install it there.

OK, but it will alert error in install info! thanks
