### ISSUE TITLE
How are super calls handled?

### ISSUE THREAD

**Issue by gvanrossum** [ericvsmith/dataclasses#16]
I'm curious about super calls. When a data-class inherit from a non-data-class, does the generated `__init__()` method call `super().__init__()`? Before or after setting the new attributes? Similar, when a data-class inherits from another data-class, does it call `super().__init__()`? In both cases, what about inheritance?

**Comment by hynek** [comment]
The problem is that the auto-generated `__init__()` cannot know the signature of the super classes’ `__init__()` – or rather how its own arguments map to them.  Being able to reasonably call super was the original reason why we added `__attrs_post_init__`.

**Comment by gvanrossum** [comment]
OK, I see. I guess multiple inheritance is right out -- the only way it could work would be if all fields had defaults and the super-call came *before* the initialization of fields in the subclass.
