### ISSUE TITLE
[Question] Correct docstring default value using default_factory

### ISSUE THREAD

**Issue by carmocca** [ericvsmith/dataclasses#162]
Hi, given this snippet:

```python
import dataclasses
from typing import List

@dataclasses.dataclass
class Foo:
    bar: List[str] = dataclasses.field(default_factory=lambda: ["foo"])

print(Foo.__doc__)
```

which prints:
`Foo(bar: List[str] = <factory>)`

is there any way to have it be?:
`Foo(bar: List[str] = ["foo"])`

Thanks!

**Comment by ericvsmith** [comment]
No, there's not. The code would have to inspect the factory function and figure out what it returns, which in general is not possible.
