### ISSUE TITLE
License, when I want to use dataclasses.py 

### ISSUE THREAD

**Issue by derived-coder** [ericvsmith/dataclasses#170]
When I want to embed https://github.com/ericvsmith/dataclasses/blob/master/dataclasses.py
in my open source project. What does it mean for my open source license (MIT)?
Can you pls clarify this.

**Comment by ericvsmith** [comment]
I'm sorry, but I'm not capable of giving you advice about combining licenses. You'll want to contact an intellectual property lawyer. The license for this code is https://github.com/ericvsmith/dataclasses/blob/master/LICENSE.txt.
