### ISSUE TITLE
TypeError when calling super() in dataclass(slots=True) subclass

### ISSUE THREAD

**Issue by TomFryers** [ericvsmith/dataclasses#171]
Basically, [this issue](https://github.com/python-attrs/attrs/issues/102) with attrs also applies to dataclasses.

Trying to run this code
```python
from dataclasses import dataclass


@dataclass(slots=True)
class Base:
    def hi(self):
        print("Hi")


@dataclass(slots=True)
class Sub(Base):
    def hi(self):
        super().hi()


Sub().hi()
```
gives this error message.
```py
Traceback (most recent call last):
  File "...", line 16, in <module>
    Sub().hi()
  File "...", line 13, in hi
    super().hi()
TypeError: super(type, obj): obj must be an instance or subtype of type
```
Replacing `super().hi()` with `super(Sub, self).hi()` fixes this, but it's not ideal.

**Comment by TomFryers** [comment]
I think this is supposed to be on the main CPython issue tracker instead, and indeed [it already exists there](https://github.com/python/cpython/issues/90562).

**Comment by ericvsmith** [comment]
Thanks, @TomFryers. You're correct, the main tracker is the place for this. I apologize for not responding to this issue when you created it, I'm behind on lots of things!
