### ISSUE TITLE
When the method __post_init__ doesnt called?

### ISSUE THREAD

**Issue by Maksim-Burtsev** [ericvsmith/dataclasses#172]
I found the [issue](https://github.com/python/cpython/issues/90913) where was conversation about an explict call of parent's __post_init__ method using super(), but if i try this:
```python
from dataclasses import dataclass


@dataclass
class A:
    def __post_init__(self):
        print("A")


@dataclass
class B(A):
    pass


b = B()
```
it will output:
```python
>> A
```
So, parents method works without explict call. 

1. I don't understand what talk about was in this issue or problem with inheritence was solved? 
2. In which case __post_init__ method of dataclass doesnt called?

**Comment by ericvsmith** [comment]
This repository is only for the 3.6 backport of dataclasses. For actual bugs in the current version dataclasses, please use the main python bug tracker. But this sounds more like a usage question, which you could ask on discuss.python.org or stackoverflow.

**Comment by Maksim-Burtsev** [comment]
> This repository is only for the 3.6 backport of dataclasses. For actual bugs in the current version dataclasses, please use the main python bug tracker. But this sounds more like a usage question, which you could ask on discuss.python.org or stackoverflow.

I got it, thanks!
