### ISSUE TITLE
cannot find 'CroppingInfo' in the module 

### ISSUE THREAD

**Issue by sosie-js** [ericvsmith/dataclasses#175]
Hello I am stalled with this error cannot find 'CroppingInfo' in the module 
when I install it locally in core/types of vspreview requiring it
from python3.10
It installs dataclasses-0.6 which lack of CroppingInfo that may be provided with newer dataclasses version ie 0.8 but refuse to install due to requirement constraints?

**Comment by Setsugennoao** [comment]
Are you some sort of troll AI

**Comment by LightArrowsEXE** [comment]
This has NOTHING to do with the dataclass module

**Comment by sosie-js** [comment]
temporary weirdness. Thanks for not persecuting me. People in china are over organ harvesting and I am using your project to check and produce pieces of the video of the nine commentaries on the CCP. ninecommentaries.com . Chinese people wake up to the truth qnd quit CCP since 2005 - we a have more 430million of demissions now. Covid-19 killed 400Million poor chinese people and destroy humanity. We have 1 billion petition coming to stop the persecution of [falun gong](https://faluninfo.net/). 

I spend extra time having to handle karma which appears like conflict like here. I don't know what happened and I had this issue of dataclasses but now it is solved and I changed nothing on the copied file that refuse to be viewed temporarily blocked by karma.

I accept you sentence of be banned, this may be paying back my karma to you. But Please follow truthfulness, compassion and forbearance and not be lead by anger, it is not good for your health and future. The issue is solved I point just you  that the package 0.7.1 has an error nicefully encode-decode. You may not be able to correct it back after it is pushed with pip3 - don't worry It is ok we don't need to fight. I am a Falun Dafa pratictionner I will not go to discord and accept I have annoyed you with little thing. Sorry for this. Have a nice day.

[Oli from France](facebook.com/olivier.lutzwiller/)

**Comment by sosie-js** [comment]
Issue solved itself (karma).

**Comment by sosie-js** [comment]
Sorry to say to both of you @Setsugennoao  and @LightArrowsEXE , your behavior were extremely shocking and inappropriate as I tracked the bug : lsmas plugin makes vspreview-0.7.1 fail whereas bestsource plugin not. 
Maybe with tolerance and benevolence you can have add a "try: ... except:" on the buggy line  for sure and have more humility not to ban me.  Here is the demo 


https://github.com/ericvsmith/dataclasses/assets/70700670/6effe403-7916-4f65-9d1c-681586cdb3a0

**Comment by sosie-js** [comment]
@bubblemint864 can you submit this to them as I can no post any patch? Thanks
```
   # status bar
    def STATUS_FRAME_PROP(self, prop: Any) -> str:
        try:
            pict = prop['_PictType'].decode('utf-8')
        except KeyError:
            pict = '?'
        except AttributeError:
            pict = prop['_PictType'].encode('utf-8')
        return 'Type: %s' % ( pict )
```

**Comment by LightArrowsEXE** [comment]
1. This fallback [already exists](https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/blob/2764b9494a97b56c969e2f0a16def53f4d114e76/vspreview/main/window.py#L96). In fact, this was changed *[over 9 months ago](https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview/commit/0148c3968beaeb65802edd8d6c20de978725dad6)*. We're not going to update a previous version. Update like we've told you in previous issues.
2. Stop polluting an issue in a repo that has NOTHING to do with your issue.
3.

>inappropriate behaviour

All your issues and complaints have been frivolous, you refuse to use an updated version for whatever reason, and you're bringing this into a repository that, as I've said multiple times so far, has NOTHING to do with your problem. 

I was likely going to unban you if you ever visited the discord and were civil, but consider this to be your notice that the ban is permanent unless I see you make *actually useful* issues in related (updated) Vapoursynth repositories and that you've learned how to properly diagnose said issues without spamming issue trackers with "fixes" for old versions when the bug has already been resolved a long time ago.

**Comment by sosie-js** [comment]
No worry [it's ok](https://www.ganjingworld.com/fr-FR/video/1fs1h0pnpt22vtBy3jaJc5VJx1031c). Problem solved. Sorry All 
Eric:  For the CroppingInfo I think it was due to a low level of memory and I never said it was related to vspreview -
Others:  I have now way to go on discord, Using python official version of apt. For now 3.10 is the validated one by ubuntu - I will not change it because project is multiarch / mutli os  .

Thanks for your comprehension and have a good day
