### ISSUE TITLE
Possibility to make dataclasses iterable or indexable

### ISSUE THREAD

**Issue by ilevkivskyi** [ericvsmith/dataclasses#21]
Imagine users who are currently using named tuples or dictionaries as objects. They probably would want to switch to dataclasses when they appear, but probably in their code they have something like:
```python
name, age = person
# or
person['name'] = 'Eve'
```
I think it may easier for them to switch to dataclasses if we provide something like this:
```python
@data(iterable=True)
class Point:
    x: int
    y: int
origin = Point(0, 0)
x, y = origin  # OK

@data(indexable=True)
class Person:
    name: str
    age: int
person =  Person('John', 31)
name = person['name']
person['age'] = 32
```
I am not sure, but I think both flags should be ``False`` by default. If ``iterable`` is enabled, then we would add a corresponding ``__iter__``, for ``indexable`` we would add ``__getitem__`` and (depending on the mutability/hashability flags) ``__setitem__``.

**Comment by gvanrossum** [comment]
I dunno. These flags might be easy to implement, but they are likely to encourage users to just use the legacy interface exclusively, using the class definition in the way NamedTuple or TypedDict are used. Let them use those.

**Comment by ilevkivskyi** [comment]
> but they are likely to encourage users to just use the legacy interface exclusively, using the class definition in the way NamedTuple or TypedDict are used. Let them use those.

I see your point, but ``TypedDict``s are just plain dicts, and don't have some features that dataclasses will have, also sometimes ``x, y = point`` may be just convenient.

**Comment by ericvsmith** [comment]
attrs has `attr.astuple`, so this could be written as `x, y = attr.astuple(point)`, which its grant you is a fair amount of typing. But one design goal is to not "accidentally" act as a tuple. We don't want `(2, 3) == point` to work, or `point3d == date`, just because both have 3 members.

**Comment by ilevkivskyi** [comment]
> But one design goal is to not "accidentally" act as a tuple. We don't want ``(2, 3) == point`` to work, or ``point3d == date``, just because both have 3 members.

Yes, this is why I propose the ``iterable=True`` and ``indexable=True`` as explicitly opt-in. Second, even with ``__iter__`` and ``__getitem__`` defined, ``__eq__`` is an independent method, so that ``point3d == date`` will still return ``False``.

**Comment by hynek** [comment]
But what is the point of it?  If ppl wanted a class-lookalike that behaves like a tuple we already have that: namedtuples.

**Comment by ilevkivskyi** [comment]
> But what is the point of it? If ppl wanted a class-lookalike that behaves like a tuple we already have that: namedtuples.

I could imagine that some people will want to switch to dataclases from named tuples and/or ``TypedDict``s, since dataclasses provide more functionality. Moreover, they might want to switch precisely for the fact that ``point3d == date`` will return ``False`` with dataclasses, while it may return ``True`` for named tuples.

At the same time I think _unpacking_ a dataclass instance is a reasonable thing to do. Also, there is a chance that existing code uses something like ``x, y, z = point3d``. Anyway, this is proposed as an opt-in behaviour

**Comment by ilevkivskyi** [comment]
As an alternative, I would propose ``asdict`` and ``astuple`` as _methods_, this looks reasonable to me:
```python
from dataclass import data

@data
class Point3D:
    x: int
    y: int
    z: int = 0

origin = Point(0, 0)
x, y, z = origin.astuple()
```
We may add a leading underscore ``_astuple`` to avoid collisions, and it will be similar to existing ``_asdict`` for named tuples.

**Comment by ericvsmith** [comment]
In #8 we decided to use module-level functions instead of instance methods.

**Comment by ericvsmith** [comment]
That said, it's valid that:

1. we could offer an opt-in way to say that we want this class have iterable and/or indexable instances

1. `__eq__` would prevent the `data == point3` problem.

**Comment by ericvsmith** [comment]
Since we added `asdict` and `astuple` in #26, I'm going to close this issue. I want to simplify things as I write the PEP. If there's demand, we can add something to address this at a later date.
