### ISSUE TITLE
__slots__ should be present by default, and other name for corresponding kwarg

### ISSUE THREAD

**Issue by ilevkivskyi** [ericvsmith/dataclasses#22]
Currently ``__slots__`` are not set by default (``slots=False``). I have two points here:
* This is not what user would expect, since dataclasses will be probably used for something that is present in large quantities, so that they should be lightweight. Also in other languages analogs of dataclasses are typically not extendable after creation.
* I would rather choose a different name for the corresponding kwarg, some people may not be familiar with slots and how they work. Maybe something like ``extendable`` that is ``False``?

**Comment by gvanrossum** [comment]
I wonder if you're being misled by the code name "dataclasses"? The intent really is to have the resulting classes be as similar to "regular" classes as possible. Turning slots on by default seems to go against that desire.

**Comment by ilevkivskyi** [comment]
> The intent really is to have the resulting classes be as similar to "regular" classes as possible. Turning slots on by default seems to go against that desire.

Even in this case I would choose a different name than ``slots`` for the kwarg. From my experience many people have no idea what they are, and I would like dataclasses to be easy to use by beginners. Some other ideas for the kwarg are ``light``, ``fixed``. But currently I like ``extendable`` most.

I am find with setting ``extendable=True`` by default, then people who don't want this will see this in the docs and switch it off if they want.

**Comment by gvanrossum** [comment]
Honestly slots are overrated -- they rarely make a difference, so I think it's all right if the name is obscure. I like the rule that the keywords correspond to the dunder method/attribute they control.

**Comment by Daenyth** [comment]
From what I've gathered on gitter, it sounds like dataclasses should be able to be part of inheritance hierarchies, unlike NamedTuples, so a flag like `extendable=False` would potentially be fairly confusing, since it could still be inherited from, regardless of whether or not fields could be added.

**Comment by ilevkivskyi** [comment]
After thinking about this again, it looks like the current behaviour is right (``__slots__`` are _opt-in_), so I am closing this issue.
