### ISSUE TITLE
How to specify factory functions

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#24]
In #3, we discussed mutable defaults which included talk of factory functions. Having resolved #3, this issue is about how to specify default value factory functions.

Some options:

1. A new parameter to `field()`. For now, let's call it `factory`:
```
   @dataclass
    class Foo:
        x: list = field(factory=list, repr=False)
```
It would be an error to specify both `default=` and `factory=`.

2. Re-use the `default` parameter to `field()`, marking it as a factory function so we can determine whether to call it. For now, let's mark it by using `Factory(callable)`.
```
    @dataclass
    class Foo:
        x: list = field(default=Factory(list), repr=False)
```

3. Have a separate flavor of `field` used with factory functions. For now, let's assume it's called `factory_field`. It would not have a `default=` parameter:
```
    @dataclass
    class Foo:
       x: list = factory_field(list, repr=False)
```

I don't have a real preference among these. I sense we should go with whatever makes mypy's life easier, but I don't know what that would be. I suspect it would be 3, since I think mypy could be told that the type of `factory_field(callable)` is the type of `callable()`. But I'm just hypothesizing, and am interested in the opinion of experts.

**Comment by gvanrossum** [comment]
While mypy (and, perhaps more importantly, PEP 484) can easily distinguish between all these using overloading, I do agree that (3) feels the easiest to implement in mypy. Moreover, if we later end up favoring another form, it's trivial to map from (3) to (1) or (2) -- it would be less simple to back out (1) or (2).

FWIW I'm not so keen on using the name "factory" here, since it doesn't have much of an association with "default". After all the factory is only used to generate a default when no explicit initial value is given (right? unlike validation or transformation). But `field_with_default_factory(list)` does sound a bit of a mouthful, and I don't have a better idea right now.

**Comment by ericvsmith** [comment]
Yes, you're correct on when the default factory is used: only when no explicit initial value is given.

Okay, I'll code that version up. I'll go with `field_with_default_factory()` for now, and when we get back to bikeshedding we can change it.

On a somewhat related note, what can PEP 484 do with:
```
    @dataclass
    class Foo:
        x: list = field(repr=False)
```
That is, where there's no type information at all in the call to `field()`? Would there be an override that specifies that when no `type` or `default` is given, that the return type is Any?

Note that `type` will only be specified in the dynamic `make_class()` scenario. In the normal `@dataclass` case, it's an error to specify it. So in the normal `@dataclass` case, the type information, if any, would have to come from the type of the `default` value.

**Comment by ericvsmith** [comment]
For fields with default factory functions that are not included in `__init__`, I'm going to call the factory from `__init__` every time, as opposed to calling it just once at class creation time to set a class variable.

For example:
```
    @dataclass
    class C:
        created: datetime.datetime=\
            field_with_default_factory(datetime.datetime.now, init=False)
```
will more or less generate:
```
    class C:
        def __init__(self):
            self.created = datetime.datetime.now()
```
as opposed to:
```
    class C:
        created = datime.datetime.now()
        def __init__(self):
            pass
```
Experimentally, this is what attrs does, too.

**Comment by ilevkivskyi** [comment]
From mypy point of view, I think (1) and (3) are almost equally easy/hard to implement. Also the fact that we will have two complex functions with the same API seems suboptimal to me:
```python
def field(name=None, type=None, *, default=_MISSING,
          repr=True, hash=None, init=True, cmp=True): ...
# and
def field_with_default_factory(name=None, type=None, *, default_factory=None,
                               repr=True, hash=None, init=True, cmp=True): ...
```
I think we should go with the first version:
```python
@dataclass
class Foo:
    x: list = field(factory=list, repr=False)
```
Also I think that ``name`` and ``type`` arguments should not appear in _function_ field. They are of course will be present in the _class_ ``Field``, but those two will be filled in automatically using ``__dict__`` and ``__annotations__``.

**Comment by ilevkivskyi** [comment]
@ericvsmith 
> I'm going to call the factory from ``__init__`` every time

This makes perfect sense to me.

**Comment by ericvsmith** [comment]
@ilevkivskyi : The reason that `name` and `type` are in the function `field()` is to support dynamic class creation using `make_class()`:
```
C = make_class('C',
               [field('x', int),
                field_with_default_factory(callable, 'y', list),
                ])
```
being the same as:
```
@dataclass
class C:
    x: int
    y: list=field_with_default_factory(callable)
```
We could create another set of functions that are just like `field` and `field_with_default_factory` but without `name` and `type`, but then we'd have to name them and document the differences. As the code currently stands, it's an error to supply them when using them in "normal" class syntax. Although doing so would give us some better flexibility in the order and naming of parameters, especially in `field_with_default_factory`. I'm not wild about the order of (callable, name, type) when using `make_class()`, but it improves just specifying the callable better in normal class syntax (as in my second example above). I'm open to suggestions.

**Comment by ilevkivskyi** [comment]
@ericvsmith 
> The reason that name and type are in the function ``field()`` is to support dynamic class creation using ``make_class()``

OK, I see, this makes sense. I don't think we should have twice more functions just to accommodate these two use cases, since again the API is almost identical. I think ideally we should have only _one_ function ``field``.

I also would like to reiterate, difference between implementing variants (1) and (3), and even (2) is relatively small, so I don't want this to affect the actual API design decision, we should think about convenience of use. ("1 second every time by thousands of users" > "1 hour once by me or other mypy devs").

**Comment by ericvsmith** [comment]
@ilevkivskyi 👍 
> I also would like to reiterate, difference between implementing variants (1) and (3) ...

I haven't forgotten this part. I hope to discuss it with @gvanrossum today and get his opinion. I agree that the long and similar argument lists to `field()` and `field_with_default_factory()` are at least a slight code smell. It would also mean we wouldn't have to come up with a better name for `field_with_default_factory`. After having played with it a bit, I'm beginning to agree with Guido that if we go with (1), the parameter should be named `default_factory`.

**Comment by ilevkivskyi** [comment]
> I'm beginning to agree with Guido that if we go with (1), the parameter should be named ``default_factory``.

Yes, makes sense.

**Comment by ericvsmith** [comment]
I just discussed this with @gvanrossum. We're going to go with option 1, as advocated by @ilevkivskyi: `field()` will have 2 parameters `default` and `default_factory` (in addition to the existing parameters that `field()` provides). The stub for `field()` will have 3 overloads:

- The type of `field(default=value, ...)` will be the type of `value`.
- The type of `field(default_factory=callable, ...)` will be the type of `callable()`.
- The type of `field(...)` (with neither `default` nor `default_factory` specified) will be `Any`.

(Here, `...` signifies other parameters to `field()`, such as `init`, `cmp`, `hash`, etc.)

Providing both `default` and `default_factory` will be an error that `field()` will catch and raise a `ValueError`.

**Comment by gvanrossum** [comment]
@ilevkivskyi could you quickly test if those overloads actually work?

**Comment by ilevkivskyi** [comment]
I tried this:
```python
T = TypeVar('T')

@overload
def field(init: bool = ...) -> Any: ...
@overload
def field(default: T = ..., init: bool = ...) -> T: ...
@overload
def field(default_factory: Callable[[], T] = ..., init: bool = ...) -> T: ...

def test() -> List[int]:
    ...

reveal_type(field()) # Revealed type is 'Any'
reveal_type(field(default=42)) # Revealed type is 'builtins.int*'
reveal_type(field(default_factory=test)) # Revealed type is 'builtins.list*[builtins.int]'
```
so it works, but in addition I get these errors on the definition
```
11: error: Overloaded function signatures 1 and 2 overlap with incompatible return types
11: error: Overloaded function signatures 1 and 3 overlap with incompatible return types
```
Here I tend to think this is a bug in mypy, and we could consider allowing ``Any`` return for overlapping signatures, but it is better to ask @JukkaL. In any case a simple ``# type: ignore`` in the stub solves this.

**Comment by ilevkivskyi** [comment]
In the actual stub the arguments will be probably keyword-only, I tried and they work as well after plain asterisk ``*,``

**Comment by ericvsmith** [comment]
Right. The current signature is:
```
def field(name=None, type=None, *, default=_MISSING,
          default_factory=_MISSING, repr=True, hash=None, init=True,
          cmp=True):
```
Thanks for your research. Can I assume this means option 1 is workable as far as mypy is concerned?

**Comment by ilevkivskyi** [comment]
> Can I assume this means option 1 is workable as far as mypy is concerned?

I think yes.

**Comment by ericvsmith** [comment]
I've implemented option 1, using the parameter name default_factory.

**Comment by ericvsmith** [comment]
Reopening to point out how attrs does factory functions. It's basically my original 2: `field(default=Factory(callable), ...)`. The `attr.Factory` class has an additional optional parameter: `takes_self` http://www.attrs.org/en/stable/api.html#attr.Factory. The docstring says: `Pass the partially initialized instance that is being initialized as a positional argument`. That seems like a useful feature, and allows a factory function for a field to depend on earlier defined fields.

But requiring the separate `Factory()` seems like a lot to pay for a feature that would be used only infrequently. We could do something horrible like inspect the callable, and if it takes one parameter, pass self. See below for attrs discussions of such magic.

I'm only bringing this up for completeness. As with most of these issues, the attrs team has put a lot of good thought in to it.

See https://github.com/python-attrs/attrs/pull/178 and https://github.com/python-attrs/attrs/issues/189.

**Comment by ilevkivskyi** [comment]
I think the use cases where one needs to use previously defined attributes can be (and probably should be, TOWTDI) solved by ``__post_init__``, for example:
```python
@dataclass
class C:
    x: int
    y: int
    coords: List[int] = None  # just a placeholder

    def __post_init__(self):
        self.coords = [self.x, self.y]
```

**Comment by ericvsmith** [comment]
@ilevkivskyi : yes, that does seem like a better way to do multi-field initialization. We can give an example in the documentation. So, let's leave `default_factory` like we have it.
