### ISSUE TITLE
Get rid of make_class().

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#27]
After talking to @raymondh today, he questioned the need for `make_class()` and its many parameters. And he's correct: it's not needed. Python can already dynamically create classes, just leverage that.

So, I plan to remove `make_class()`.

Instead of:
```
C = make_class('C',
               [field('x', int),
                field('y', int, default=5),
                ])
```
We'd use: 
```
cls_dict = {'__annotations__': OrderedDict(x=int, y=int,),
            'y': field(default=5),
            }
C = dataclass(type('C', (object,), cls_dict))
assert repr(C(4)) == 'C(x=4,y=5)'
```
And the beauty of this is that I can remove the `name` and `type` parameters to `field()`.

**Comment by ericvsmith** [comment]
Further, `make_class()` was incomplete, and could not do everything you can do with `type()`. For example, it couldn't specify additional methods.

**Comment by ilevkivskyi** [comment]
I think we should keep ``make_class`` but make it just a simple utility function that would delegate to ``dataclass`` and would look approximately like this:
```python
def make_dataclass(cls_name: str,
                   fields: Iterable[Union[Tuple[str, Type], Tuple[str, Type, Field]]],
                   bases=(), ns=None):
    anns = OrderedDict((name, tp) for name, tp, *_ in fields)
    ns = ns or {}
    ns['__annotations__'] = anns
    for item in fields:
        if len(item) == 3:
            name, tp, spec = item
            ns[name] = spec
    cls = type(cls_name, bases, ns)
    return dataclass(cls) 
```
I think programmatic creation of dataclasses will be useful, and providing a utility function that just takes care of ``__annotations__`` etc. will be helpful (it is however not necessary to devote any attention to it in the PEP). Example use:
```python
C = make_dataclass('C',
                   [('x', int),
                    ('y', int, field(default=5)),
                    ns={'add_one': lambda self: self.x + 1}])
```

Note that with the proposed signature we can remove ``name`` and ``type`` parameters to ``field`` as well, I am +1 on removing them.

**Comment by ericvsmith** [comment]
@ilevkivskyi : I agree that's a reasonable interface and implementation of a new, simpler `make_class()` (although modifying the passed-in namespace seems a little icky, but we can discuss that later).

But I think it still doesn't provide all of the possible functionality, such as metaclasses, exposed for example in `types.new_class()`.

In any event, I'm going to merge my PR #29 and drop the existing `make_class()` and references to it in the PEP. I'll have the PEP contain a simple example, such as in my [comment above]( https://github.com/ericvsmith/dataclasses/issues/27#issue-255784324).

I'm going to leave this issue open, as a reminder to address it later. Whether that's in dataclasses.py itself, or in a dataclasses_tools on PyPI, or just through docs, we can decide later.

I think the PEP is improved by focusing on:

> `dataclass` is just a function, usually but not always used as a decorator, that will add some methods to your class. You provide the class, using a class statement or whatever mechanism you want, subject to a few simple rules, and it does the rest.

**Comment by ericvsmith** [comment]
I've added `make_dataclass()` back in PR #68.
