### ISSUE TITLE
Add type annotations to generated code

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#4]
Presumably we want type annotations added to the generated methods, in particular `__init__`. This is a reminder to add annotations.

**Comment by ericvsmith** [comment]
Given a class:

```
@dataclass(frozen=True,hash=True)
class C:
    x: int = 0
    y: float = 3.14
```
The code basically generates these functions with annotations:

```
def __init__(_self, x:int=_MISSING, y:float=_MISSING):
    object.__setattr__(_self,'x',type(_self).x if x is _MISSING else x)
    object.__setattr__(_self,'y',type(_self).y if y is _MISSING else y)

def __repr__(_self)->str:
    return _self.__class__.__name__ + f"(x={_self.x!r},y={_self.y!r})"

def __hash__(_self)->int:
    return hash((_self.x,_self.y,))

def __eq__(_self, _other)->bool:
    if _other.__class__ is _self.__class__:
        return (_self.x,_self.y,)==(_other.x,_other.y,)
    return NotImplemented

def __ne__(_self, _other) -> bool:
    result = _self.__eq__(_other)
    return NotImplemented if result is NotImplemented else not result

def __lt__(_self, _other)->bool:
    if _other.__class__ is _self.__class__:
        return (_self.x,_self.y,)<(_other.x,_other.y,)
    return NotImplemented

def __le__(_self, _other)->bool:
    if _other.__class__ is _self.__class__:
        return (_self.x,_self.y,)<=(_other.x,_other.y,)
    return NotImplemented

def __gt__(_self, _other)->bool:
    if _other.__class__ is _self.__class__:
        return (_self.x,_self.y,)>(_other.x,_other.y,)
    return NotImplemented

def __ge__(_self, _other)->bool:
    if _other.__class__ is _self.__class__:
        return (_self.x,_self.y,)>=(_other.x,_other.y,)
    return NotImplemented

def __setattr__(self, name, value):
    raise FrozenInstanceError()

def __delattr__(self, name):
    raise FrozenInstanceError()

```
Are these annotations (like `bool` for comparisons or `str` for `__repr__`) overkill?

Should `_self` and `_other` have annotations?

**Comment by gvanrossum** [comment]
Who would see these annotations? Definitely not a static type checker like mypy, PyCharm or pytype.

I guess someone could introspect the annotations at runtime. But that also seems an unlikely use case (usually that's done for the benefit of argument checking, and I think you don't need that). So I think it's overkill and perhaps a little bit wasteful (all those functions would have `__annotations__` dicts that nobody will look at).

PS. The `self` / `_self` parameter should almost never have a type annotation (except for something like a `__copy__` method or a `create` factory class method); `other` should be annotated `object` or `Any` (EIBTI).

**Comment by ericvsmith** [comment]
Okay, I'll remove the return types, at least.

**Comment by ilevkivskyi** [comment]
I would keep only the ``__init__`` annotations:
```python
def __init__(_self, x: int = _MISSING, y: float = _MISSING) -> None: ...
```

**Comment by gvanrossum** [comment]
I'm with Ivan, actually.
