### ISSUE TITLE
covariant overriding of fields considered unsafe

### ISSUE THREAD

**Issue by gvanrossum** [ericvsmith/dataclasses#45]
I don't recall where I saw this but I believe we had some example where a base class would declare a field of type `float` and the subclass would redefine it as `int`. I would just like to insert a note in that thread referencing https://github.com/python/mypy/issues/3208, which points out that this is not actually a safe thing to do unless the class is immutable.

**Comment by ilevkivskyi** [comment]
Yes, but mypy currently only rejects this for protocols (which are deliberately more strict in some aspects), so technically speaking the example will pass, but I agree ``Any`` (probably in supertype) may be better for covariant mutable overriding example.

**Comment by ericvsmith** [comment]
It was in a test. 

```
        # Note that x from C1 replaces x in Base, but the order remains
        #  the same as defined in Base.
        @dataclass
        class Base:
            x: float = 15.0
            y: int = 0

        @dataclass
        class C1(Base):
            z: int = 10
            x: int = 15
```
I'm not sure we're using "super" and "sub" the same way here. Should the type of `x` be `Any` in `base`, or in `C1`?

**Comment by ilevkivskyi** [comment]
I think it would be better with ``Any`` in ``Base``.
