### ISSUE TITLE
Spaces in repr

### ISSUE THREAD

**Issue by Drekin** [ericvsmith/dataclasses#47]
It's a tiny issue, but shouldn't there be spaces after commas in the generated reprs, i.e. `Point(x=1, y=2)` instead of `Point(x=1,y=2)`?

**Comment by ilevkivskyi** [comment]
+1 for space, it looks nicer, and more like one would write under PEP 8.

**Comment by ericvsmith** [comment]
I was omitting the spaces because I thought that's what namedtuples do, but I'm wrong:
```
>>> from collections import namedtuple
>>> namedtuple('T', 'x y z')(1, 2, 3)
T(x=1, y=2, z=3)
```
I'll put the spaces in.
