### ISSUE TITLE
PEP: Add examples of using eq, compare, hash, and frozen.

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#50]

**Comment by ericvsmith** [comment]
I think the existing PEP wording and examples are sufficient.

**Comment by pylang** [comment]
In the PEP example, would you consider adding empty lines between methods for readability?

**Comment by ericvsmith** [comment]
Well, it's not like I expect anyone to read that code. You're supposed to look at it and think: "Man, I really hate writing stuff like that. Good think I'll never need to write it again."

So, I'd rather leave it as-is.

**Comment by pylang** [comment]
I see your point that it is boilerplate, but I'm not sure I understand the assumption people won't read it.  I read through it to grasp which special methods were abstracted by `@dataclass`.  I think it's a good comparison of equivalent code.  

Thanks.
