### ISSUE TITLE
Return type of asdict()

### ISSUE THREAD

**Issue by Dutcho** [ericvsmith/dataclasses#56]
Suggest to have `asdict()` return an `OrderedDict `(like `fields()` already does) as order matters in a `dataclass`

**Comment by ilevkivskyi** [comment]
There is already PR https://github.com/ericvsmith/dataclasses/pull/52 that will fix this.

**Comment by Dutcho** [comment]
sorry for duplication, didn't see it there

**Comment by ilevkivskyi** [comment]
No problem, I just wanted to link the PR in this issue.

**Comment by ericvsmith** [comment]
@ilevkivskyi : Apologies for not getting to your PRs yet. Real life is in the way, but I hope to make some progress this week.

I'm going to close this issue, and put comments on PR #52.
