### ISSUE TITLE
Type annotation for module-level functions

### ISSUE THREAD

**Issue by Dutcho** [ericvsmith/dataclasses#58]
Which type annotation would be appropriate for `fields()`, `astuple()`, `asdict()`? Because `dataclass`es don’t derive from a common ancestor, a protocol `SupportsFields` would be required to properly specify

```
> echo import dataclasses; dataclasses.astuple((1, 2, 3)) >xxx.py
> mypy xxx.py
```
(no warnings, as `astuple()` doesn't have a type annotation)

**Comment by ilevkivskyi** [comment]
The annotations will not be added to ``dataclasses`` module in stdlib, they will be added to typeshed. Using a protocol is a possible good solution, but anyway dataclasses will require some special-casing in mypy. For example:
```python
@dataclass
class C:
    a: int
    b: str

x = astuple(C(1, 'a')) # mypy will know that 'x' has type 'Tuple[int, str]'
```
I am going to take care of this when API will be fixed and/or PEP is accepted.

**Comment by ericvsmith** [comment]
See python/mypy#4792.
