### ISSUE TITLE
Add a module-level helper to detect if an object is a dataclass

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#63]
This would be just checking for the existence of `_MARKER` (which is currently `"__dataclass_fields__"`). Proposed name `isdataclass(obj)`.

**Comment by taleinat** [comment]
Why is this needed? By design. this is just a utility in the definition of normal classes.

As a precedent, I don't think there's a way to tell whether something is a `namedtuple`.

**Comment by ericvsmith** [comment]
For namedtuple, it comes up every now and again on stackoverflow and bugs.python.org. For example, here's one such example on bpo: https://bugs.python.org/issue7796. Note @rhettinger's response at https://bugs.python.org/issue7796#msg99869, where he "blesses" checking for the existence of `_fields`. The `dataclass` equivalent would be to check for `__dataclass_fields__`, which I guess we could live with. But, since unlike `nametuple` we have a convenient place to put helper functions (at the module level), and given that `attrs` has `attr.has()`, it seems logical to add `isdataclass()`.

The reason people want this functionality, translated to `dataclass` terms, is that they want to iterate over the fields for some reason. Currently, you'd have to call `fields()` and be prepared for the undocumented `AttributeError` (EAFP vs. LBLY). I guess instead of adding `isdataclass()` we could embrace EAFP instead, by having `fields()` return a `ValueError` for a non-dataclass and document that behavior.

**Comment by taleinat** [comment]
What about having a sentinel mix-in class which is injected into the bases, so that users could just use `isinstance()` and `issubclass()` as usual? I feel that would be more consistent with existing expectations.

**Comment by ericvsmith** [comment]
I'm opposed to always having a mixin class that's added. The whole point is that these are just normal classes, and we don't mess with bases, metaclasses, etc. That's for the user to control.

I wouldn't necessarily be opposed to providing such an optional mixin that users could opt in to, by using it themselves. But I'm not sure that's very useful.

In any event, I'd like to add `isdataclass()` to the PEP and implementation.

**Comment by ilevkivskyi** [comment]
Just as a data point I am also against the mixin class. The reason that I think was not mentioned yet is performance: re-creating the class with a mixin can be slow.

**Comment by ericvsmith** [comment]
Closed by #66.
