### ISSUE TITLE
Common protocol with attrs?

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#65]
As discussed in #52, is there any way that dataclasses and attrs could share a protocol that would make things like serialization easily shareable between them?

**Comment by hynek** [comment]
Can you be more specific about what you had in mind?

**Comment by ericvsmith** [comment]
It came from suggestion on that thread that maybe there could be a way to detect that something is a dataclass/attrs instance, and use common code for serialization (asdict(), astuple(), etc.). I think it started here: https://github.com/ericvsmith/dataclasses/pull/52#issuecomment-344320706.

**Comment by ericvsmith** [comment]
I can't come up with any use case for this (or even how it would work), so I'm closing this.
