### ISSUE TITLE
Which fields to expose in dataclasses.fields()?

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#75]
As pointed out in https://github.com/ericvsmith/dataclasses/issues/17#issuecomment-346228665, there are now 3 kinds of fields: regular fields, `InitVar` fields, and `ClassVar` fields.

With the addition of `InitVar`s (see #17), the internal `__dataclass_fields__` class variable now needs to store the `InitVar` fields in order to correctly compute derived class `__init__()` params. I keep track of which type each field is with an undocumented `Field._field_type` member. I don't think I even keep track of the `ClassVar` fields, since I don't need them for anything.

The question comes up: which fields are returned by `dataclasses.fields()`? As I currently have it implemented, it returns just the regular fields, not the `InitVar` or `ClassVar` fields. If we decide it needs to return the latter two, I'll have to expose the `_field_type` by renaming it, and give it better values that can be more easily consumed.

I'm leaning toward only returning the regular fields. We can always expose the other field types in the future, maybe by a new param for `fields()` indicating which types to return, or by a new API like `dataclasses.all_fields()`.

I see the main reason for `fields()` is for serializers and the like to see what data is in each instance, and for that they only need the regular fields. But maybe I'm not thinking big enough, and there's some use for `InitVar`s in particular.

**Comment by ilevkivskyi** [comment]
I think it should be only regular fields, since the main use case would be to actually access those fields on an instance. I think having to use ``hasattr()`` of ``try: ... except: ...`` defeats the purpose of ``fields()``.

**Comment by ericvsmith** [comment]
Well you could do `if f.field_kind == 'regular': val=getattr(inst, f.name)` [0], but yeah, it does seem like just regular fields are the ones of value.

[0] Or whatever a check for the kind of field would look like.

**Comment by ericvsmith** [comment]
I'm going to leave `fields()` as just returning regular fields. If needed, we can add another API in the future.
