### ISSUE TITLE
Module-level functions or instance methods for helpers

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#8]
There is a need to have a number of helper functions, such as asdict(), astuple(), replace(), etc. This issue is not about which specific functions we need (that will come later), but rather how to make these functions available.

namedtuple handles this by having member functions that begin with an underscore, such as ._make(), ._asdict(), ._replace(), ._fields(), etc.

attrs handles this by using module-level functions that take an instance as a parameter, such as .attrs.fields(), attrs.has(), attrs.asdict(), etc.

I'm leaning towards the attrs interface of using module-level functions. I don't like the underscores required by namedtuple's approach, and even then you could have name collisions.

**Comment by gvanrossum** [comment]
But now you have to import the module (I guess it also contains the class decorator and field() factory).

Is there a good reason to allow fields starting with `_` here? (There may well be.)

**Comment by ericvsmith** [comment]
Yes, if they're module functions you'd have to import them along with the decorator and field().

from dataclass import dataclass, field, asdict

The usual reason for allowing fields with underscores is in the dynamic class creation case, where you're reading the fields from a database or CSV file. But it's not much of an argument, because you have to be able to remap field names, anyway. If a field is named "class" or other keyword, you'll have bigger problems. namedtuple has an "automatic field rename on collision or keyword" feature. I'm not sure how attrs handles it, if at all.

Ignoring the dynamic case, I'd be okay with saying fields can't start with an underscore, and then using _asdict, _fields, etc. Or module functions, I don't feel too strongly about it. Member functions makes for a better API, module functions gives more leeway to the user to pick names.

**Comment by warsaw** [comment]
Single leading underscore is a very strongly ingrained signal for non-public-ness of an API.  I kind of get why namedtuple chose this over module helpers since they live in the collections module.  Presumably dataclasses would have a module of their own, so that's less of a concern.

In my own uses of attr I always `import attr` rather than from-importing names out of the module.  Perhaps that's because you tend to use the module names like `@attr.s` and `attr.ib()`, but it doesn't bother me, and I'd rather have public names without the underscores.

**Comment by gvanrossum** [comment]
OK, let's go with module functions and allow leading underscores.

**Comment by ericvsmith** [comment]
Okay.

**Comment by ilevkivskyi** [comment]
Just one more possible option is to have module level functions _and_ special methods (similar to ``len()`` and ``.__len__()``).

Although I agree that module level functions are better here.
