### ISSUE TITLE
Change combination of eq=False and compare=True to a ValueError

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#88]
Carl Meyer suggests in https://mail.python.org/pipermail/python-dev/2017-November/150850.html to make `@dataclass(eq=False, compare=True)` be an error. Currently if `compare=True` then `eq` is forced to be `True`, ignoring what the user supplied.

I agree that instead of silently ignoring this combination, it would be better if a `ValueError` were raised.

**Comment by ilevkivskyi** [comment]
Indeed, ``compare`` should rather be ``order``, some (younger) people don't even know what ``cmp`` is.
On the contrary, there is ``functools.total_ordering`` class decorator.
