### ISSUE TITLE
What about conflicting methods?

### ISSUE THREAD

**Issue by JimJJewett** [ericvsmith/dataclasses#95]
There is a way to tell the decorator not to bother creating an __init__ or __repr__ ... but what happens if that more complicated form isn't used, but the user explicitly defines such methods?

e.g.

@dataclass
class C:
    def __repr__(self):
        return "ugh, a C class"

will the explicit __repr__ be silently thrown away?  Will an error be raised?

**Comment by ericvsmith** [comment]
I added wording to the PEP. It's currently an `AttributeError`, but I will probably change it to a `TypeError`.
