### ISSUE TITLE
Issue 95 glitch

### ISSUE THREAD

**Issue by JimJJewett** [ericvsmith/dataclasses#98]
"If any generated method already exists on the class, an AttributeError will be raised."

(1)  A later commit changed this to TypeError in the implementation, but did not update the PEP.

(2)  This sentence should probably be moved up to just after the bulleted list of parameters.  Right now, it looks like a detail of processing a simple (data) field, and is therefore easy to miss.  (Alternatively, maybe the field processing should all be under Field objects section?

**Comment by ericvsmith** [comment]
Thanks.
