### ISSUE TITLE
Should isdataclass return True for both classes and instances?

### ISSUE THREAD

**Issue by ericvsmith** [ericvsmith/dataclasses#99]
Raised by Carl Meyer in https://mail.python.org/pipermail/python-dev/2017-November/150850.html.

I think he's probably correct. The current behavior, where it only works on instances, is surprising. The equivalent `attrs` API, `attr.has()`, returns `True` for both classes and instances.

**Comment by gvanrossum** [comment]
I'm not keen on perpetuation confusion between classes and instances -- it makes code harder to read. E.g. when I see
```py
def foo(a):
    assert isdataclass(a)
```
I can't tell whether a is supposed to be a class or an instance.

**Comment by ilevkivskyi** [comment]
Also note that if we are going to change this, then ``asdict`` and ``astuple`` should be updated, since they use ``isdataclass`` to work only on _instances_.

**Comment by ericvsmith** [comment]
I've already verified that there's an existing test that fails if `isdataclass` is changed.

**Comment by ericvsmith** [comment]
I think I'm just going to delete `isdataclass`, since I can't come up with a good use case for it. It's easy enough to add later.

**Comment by ericvsmith** [comment]
And I can add a note that, if you feel you really need to know
